apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-tracker-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-tracker-backend
  template:
    metadata:
      labels:
        app: expense-tracker-backend
    spec:
      containers:
      - name: expense-tracker-backend
        image: expense-tracker-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql:3306/expensetracker?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "rootpassword"

---
apiVersion: v1
kind: Service
metadata:
  name: expense-tracker-backend
spec:
  selector:
    app: expense-tracker-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
