apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-tracker-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-tracker-frontend
  template:
    metadata:
      labels:
        app: expense-tracker-frontend
    spec:
      containers:
      - name: expense-tracker-frontend
        image: expense-tracker-frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: expense-tracker-frontend
spec:
  selector:
    app: expense-tracker-frontend
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 80
  type: LoadBalancer
